name: default_project
version: 0.0.1
description: default_project application that uses dartling for its model.
author: Your Name
homepage: http://ondart.me/
documentation:
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
  