name: category_keyword
version: 0.0.2
description: category_keyword application that uses dartling for its model.
author: Your Name
homepage: http://ondart.me/
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  browser: any
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
  